#spring:
#  mvc:
  #    static-path-pattern: /res/**
#  web:
#    resources:
#      static-locations: [classpath:/haha/]

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  servlet:
    context-path: /world