person:
  username: "zhang\nsan"
#  单引号会将 \n 作为字符串输出  双引号会将 \n 作为换行输出
#  双引号不会转义，单引号会转义
  boss: true
  birth: 2019/12/9
  age: 22
#  interests: [篮球,足球]
  interests:
    - 篮球
    - 足球
    - 18
  animal: [阿毛,阿狗]
#  score:
#    english: 80
#    math: 90
  score: {english:80,math:90}
  salarys:
    - 9999.8
    - 9999.9
  pet:
    name: 阿狗
    weight: 99.99
  allPets:
    sick:
      - name: 阿狗
        weight: 99.99
      - {name:阿狗,weight:99.999}
      - name: 阿虫
      - weight: 77.77
    health: [{name:阿张,weight:77.999},{name:阿名,weight:66.999}]